# Generated by Django 5.1.1 on 2024-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedfile',
            name='processed_text',
        ),
        migrations.AddField(
            model_name='processedfile',
            name='transactions_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
