# Generated by Django 5.1.1 on 2024-10-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0002_remove_processedfile_processed_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesAndAmountsDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_amount_dict', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='processedfile',
            name='categories_and_amounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
